# Generated by Django 4.1.7 on 2023-04-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeemakerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_consumption',
            field=models.DecimalField(decimal_places=18, max_digits=30, null=True),
        ),
    ]
