# Generated by Django 4.1.7 on 2023-04-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeemakerapi', '0002_alter_product_average_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
